/*
** EPITECH PROJECT, 2020
** common/include/commands/CallCommand
** File description:
** DO NOT EDIT THIS FILE MANUALLY
*/

#include "commands/CallCommand.hpp"

namespace babel {
    namespace commands {
        CallCommand::CallCommand() : AMessage("CallCommand")
        { /* ignore */ }

        CallCommand::CallCommand(babel::User::Id userId) :
            AMessage("CallCommand"), _userId(userId)
        { /* ignore */ }

        babel::User::Id CallCommand::getUserId() const
        {
            return (this->_userId);
        }
    }
}
