/*
** EPITECH PROJECT, 2020
** common/include/commands/HangUpCommand
** File description:
** DO NOT EDIT THIS FILE MANUALLY
*/

#include "commands/HangUpCommand.hpp"

namespace babel {
    namespace commands {
        HangUpCommand::HangUpCommand() : AMessage("HangUpCommand")
        { /* ignore */ }

        HangUpCommand::HangUpCommand(babel::User::Id userId) :
            AMessage("HangUpCommand"), _userId(userId)
        { /* ignore */ }

        babel::User::Id HangUpCommand::getUserId() const
        {
            return (this->_userId);
        }
    }
}
