/*
** EPITECH PROJECT, 2020
** common/include/commands/IdentifyCommand
** File description:
** DO NOT EDIT THIS FILE MANUALLY
*/

#include "commands/IdentifyCommand.hpp"

namespace babel {
    namespace commands {
        IdentifyCommand::IdentifyCommand() : AMessage("IdentifyCommand")
        { /* ignore */ }

        IdentifyCommand::IdentifyCommand(babel::User::Id userId) :
            AMessage("IdentifyCommand"), _userId(userId)
        { /* ignore */ }

        babel::User::Id IdentifyCommand::getUserId() const
        {
            return (this->_userId);
        }
    }
}
