/*
** EPITECH PROJECT, 2020
** common/include/commands/MessageCommand
** File description:
** DO NOT EDIT THIS FILE MANUALLY
*/

#include "commands/MessageCommand.hpp"

namespace babel {
    namespace commands {
        MessageCommand::MessageCommand() : AMessage("MessageCommand")
        { /* ignore */ }

        MessageCommand::MessageCommand(babel::User::Id userId,babel::Message::Body body) :
            AMessage("MessageCommand"), _userId(userId), _body(body)
        { /* ignore */ }

        babel::User::Id MessageCommand::getUserId() const
        {
            return (this->_userId);
        }

        babel::Message::Body MessageCommand::getBody() const
        {
            return (this->_body);
        }
    }
}
