/*
** EPITECH PROJECT, 2020
** common/include/commands/UpdateCommand
** File description:
** DO NOT EDIT THIS FILE MANUALLY
*/

#include "commands/UpdateCommand.hpp"

namespace babel {
    namespace commands {
        UpdateCommand::UpdateCommand() : AMessage("UpdateCommand")
        { /* ignore */ }

        UpdateCommand::UpdateCommand(babel::User::Name username,babel::User::Avatar avatar,babel::User::Visibility visibility) :
            AMessage("UpdateCommand"), _username(username), _avatar(avatar), _visibility(visibility)
        { /* ignore */ }

        babel::User::Name UpdateCommand::getUsername() const
        {
            return (this->_username);
        }

        babel::User::Avatar UpdateCommand::getAvatar() const
        {
            return (this->_avatar);
        }

        babel::User::Visibility UpdateCommand::getVisibility() const
        {
            return (this->_visibility);
        }
    }
}
