/*
** EPITECH PROJECT, 2020
** common/include/commands/UsersCommand
** File description:
** DO NOT EDIT THIS FILE MANUALLY
*/

#include "commands/UsersCommand.hpp"

namespace babel {
    namespace commands {
        UsersCommand::UsersCommand() : AMessage("UsersCommand")
        { /* ignore */ }

        UsersCommand::UsersCommand(std::size_t maxUsers) :
            AMessage("UsersCommand"), _maxUsers(maxUsers)
        { /* ignore */ }

        std::size_t UsersCommand::getMaxUsers() const
        {
            return (this->_maxUsers);
        }
    }
}
