/*
** EPITECH PROJECT, 2020
** common/include/events/ErrorEvent
** File description:
** DO NOT EDIT THIS FILE MANUALLY
*/

#ifndef ERROREVENT_HPP_
#define ERROREVENT_HPP_

#include "AMessage.hpp"
#include <string>

namespace babel {
    namespace events {
        /// \brief ErrorEvent
        class ErrorEvent : public AMessage {
            public:
                /// \brief Dummy constructor (for serialize)
                ErrorEvent();

                /// \brief Constructor of ErrorEvent class
                ErrorEvent(std::string message);

                /// \brief Deconstructor of ErrorEvent
                ~ErrorEvent() = default;

                /// \brief Getter for Message
                std::string getMessage() const;

                template<class Archive>
                void serialize(Archive &ar, const unsigned int)
                {
                    ar & _message;
                }

            private:
                std::string _message;
        };
    }
}

#endif
