/*
** EPITECH PROJECT, 2020
** common/include/events/ErrorEvent
** File description:
** DO NOT EDIT THIS FILE MANUALLY
*/

#include "events/ErrorEvent.hpp"

namespace babel {
    namespace events {
        ErrorEvent::ErrorEvent() : AMessage("ErrorEvent")
        { /* ignore */ }

        ErrorEvent::ErrorEvent(std::string message) :
            AMessage("ErrorEvent"), _message(message)
        { /* ignore */ }

        std::string ErrorEvent::getMessage() const
        {
            return (this->_message);
        }
    }
}
