/*
** EPITECH PROJECT, 2020
** common/include/events/MessageEvent
** File description:
** DO NOT EDIT THIS FILE MANUALLY
*/

#include "events/MessageEvent.hpp"

namespace babel {
    namespace events {
        MessageEvent::MessageEvent() : AMessage("MessageEvent")
        { /* ignore */ }

        MessageEvent::MessageEvent(babel::User::Id fromUserId,babel::User::Id toUserId,babel::Message::Timestamp timestamp,babel::Message::Body body) :
            AMessage("MessageEvent"), _fromUserId(fromUserId), _toUserId(toUserId), _timestamp(timestamp), _body(body)
        { /* ignore */ }

        babel::User::Id MessageEvent::getFromUserId() const
        {
            return (this->_fromUserId);
        }

        babel::User::Id MessageEvent::getToUserId() const
        {
            return (this->_toUserId);
        }

        babel::Message::Timestamp MessageEvent::getTimestamp() const
        {
            return (this->_timestamp);
        }

        babel::Message::Body MessageEvent::getBody() const
        {
            return (this->_body);
        }
    }
}
