/*
** EPITECH PROJECT, 2020
** common/include/commands/HangUpCommand
** File description:
** DO NOT EDIT THIS FILE MANUALLY
*/

#ifndef HANGUPCOMMAND_HPP_
#define HANGUPCOMMAND_HPP_

#include "AMessage.hpp"
#include "User.hpp"

namespace babel {
    namespace commands {
        /// \brief HangUpCommand
        class HangUpCommand : public AMessage {
            public:
                /// \brief Dummy constructor (for serialize)
                HangUpCommand();

                /// \brief Constructor of HangUpCommand class
                HangUpCommand(babel::User::Id userId);

                /// \brief Deconstructor of HangUpCommand
                ~HangUpCommand() = default;

                /// \brief Getter for UserId
                babel::User::Id getUserId() const;

                template<class Archive>
                void serialize(Archive &ar, const unsigned int)
                {
                    ar & _userId;
                }

            private:
                babel::User::Id _userId;
        };
    }
}

#endif
