/*
** EPITECH PROJECT, 2020
** common/include/commands/UpdateCommand
** File description:
** DO NOT EDIT THIS FILE MANUALLY
*/

#ifndef UPDATECOMMAND_HPP_
#define UPDATECOMMAND_HPP_

#include "AMessage.hpp"
#include "User.hpp"
#include "User.hpp"
#include "User.hpp"

namespace babel {
    namespace commands {
        /// \brief UpdateCommand
        class UpdateCommand : public AMessage {
            public:
                /// \brief Dummy constructor (for serialize)
                UpdateCommand();

                /// \brief Constructor of UpdateCommand class
                UpdateCommand(babel::User::Name username,babel::User::Avatar avatar,babel::User::Visibility visibility);

                /// \brief Deconstructor of UpdateCommand
                ~UpdateCommand() = default;

                /// \brief Getter for Username
                babel::User::Name getUsername() const;

                /// \brief Getter for Avatar
                babel::User::Avatar getAvatar() const;

                /// \brief Getter for Visibility
                babel::User::Visibility getVisibility() const;

                template<class Archive>
                void serialize(Archive &ar, const unsigned int)
                {
                    ar & _username;
                    ar & _avatar;
                    ar & _visibility;
                }

            private:
                babel::User::Name _username;
                babel::User::Avatar _avatar;
                babel::User::Visibility _visibility;
        };
    }
}

#endif
