/*
** EPITECH PROJECT, 2020
** common/include/commands/UsersCommand
** File description:
** DO NOT EDIT THIS FILE MANUALLY
*/

#ifndef USERSCOMMAND_HPP_
#define USERSCOMMAND_HPP_

#include "AMessage.hpp"

namespace babel {
    namespace commands {
        /// \brief UsersCommand
        class UsersCommand : public AMessage {
            public:
                /// \brief Dummy constructor (for serialize)
                UsersCommand();

                /// \brief Constructor of UsersCommand class
                UsersCommand(std::size_t maxUsers);

                /// \brief Deconstructor of UsersCommand
                ~UsersCommand() = default;

                /// \brief Getter for MaxUsers
                std::size_t getMaxUsers() const;

                template<class Archive>
                void serialize(Archive &ar, const unsigned int)
                {
                    ar & _maxUsers;
                }

            private:
                std::size_t _maxUsers;
        };
    }
}

#endif
